jwt:
  secret: "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTc1MzEyMzc5MywiaWF0IjoxNzUzMTIzNzkzfQ.opvyWVNGSFsFyj5jUAMEh4Cxc68FC-oARjZiyVcUxBs"
  rotation_period: "24h"
  ttl: "20m"
  old_keys_to_keep: 2

permissions:
  path: "C:/Users/Joker/Desktop/GO_Music/GO_Music/config/perm_config.yml"

password:
  cost: 12

cache:
  token_ttl: "20m"    
  password_ttl: "5m"  
  permission_ttl: "5m" 