roles:
  admin:
    own_records_only: false
    sections:
      - name: "Расписание"
        url: "/schedule"
        can_read: true
        can_write: true
      - name: "Занятия"
        url: "/lessons"
        can_read: true
        can_write: true
      - name: "Сотрудники"
        url: "/employee"
        can_read: true
        can_write: true
      - name: "Аудитория"
        url: "/audience"
        can_read: true
        can_write: true
      - name: "Инструмент"
        url: "/instruments"
        can_read: true
        can_write: true
      - name: "Пользователь"
        url: "/users"
        can_read: true
        can_write: true
      - name: "Ученики"
        url: "/students"
        can_read: true
        can_write: true
      - name: "Группы"
        url: "/groups"
        can_read: true
        can_write: true
      - name: "Оценки"
        url: "/grades"
        can_read: true
        can_write: true
      - name: "Посещение"
        url: "/attendance"
        can_read: true
        can_write: true
      - name: "Программа"
        url: "/programs"
        can_read: true
        can_write: true

  teacher:
    own_records_only: true
    sections:
      - name: "Оценки"
        url: "/grades"
        can_read: true
        can_write: true
      - name: "Посещение"
        url: "/attendance"
        can_read: true
        can_write: true

  student:
    own_records_only: true
    sections:
      - name: "Оценки"
        url: "/grades"
        can_read: true
        can_write: false
      - name: "Посещение"
        url: "/attendance"
        can_read: true
        can_write: false
      - name: "Инструмент"
        url: "/instruments"
        can_read: true
        can_write: false

  employee:
    own_records_only: false
    sections:
      - name: "Аудитория"
        url: "/audience"
        can_read: true
        can_write: true
      - name: "Инструмент"
        url: "/instruments"
        can_read: true
        can_write: true