name: Go CI with Coveralls

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: student
          POSTGRES_DB: KP
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Wait for PostgreSQL
      run: sleep 5  

    - name: Run tests with coverage
      working-directory: GO_Music
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_USER: postgres
        DB_PASSWORD: student
        DB_NAME: KP
        DB_SSLMODE: disable
      run: go test -coverprofile=coverage.out ./...

    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest

    - name: Send coverage to Coveralls
      env:
        COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      run: goveralls -coverprofile=coverage.out -service=github -repotoken=$COVERALLS_TOKEN