# Original author - Cyprien G, 2025
# Link to repository: https://github.com/cyprieng/github-breakout

name: generate breakout svg

on:
  workflow_dispatch:  

jobs:
  generate-svg:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: generate SVG
        uses: cyprieng/github-breakout@v1.0.0
        with:
          github_username: ${{ github.repository_owner }}

      - name: Move generated SVGs
        run: |
          mkdir -p activity
          mv output/light.svg activity/breakout-light.svg
          mv output/dark.svg activity/breakout-dark.svg

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push SVGs
        run: |
          git add images/breakout-light.svg activity/breakout-dark.svg
          git commit -m "chore: update breakout SVGs" || echo "No changes to commit"

          git push
